### ISSUE TITLE
Array of plant ids must be preceded by argument flag on every argument

### ISSUE THREAD

**Issue by polmonso** [Som-Energia/plantmonitor#41]
I believe https://github.com/Som-Energia/plantmonitor/commit/8ebe8ae2b6db924e529b574561808b4b636932eb broke the usage of solargis as

`python -m scripts.solargis dbapi apikey 2024-06-25 2024-06-25 1 2 3 4`

> Error: Got unexpected extra arguments (1 2 3 4 5 6 7 9 13 14 15 16 17 22 41) 

which now has to be 

`python -m scripts.solargis dbapi apikey 2024-06-25 2024-06-25 --plant-ids 1 --plant-ids 2 --plant-ids 3 --plant-ids 4`

I also tried 

`python -m scripts.solargis dbapi apikey --from-date 2024-06-25 --to-date 2024-06-25 1 2 3 4`

**Comment by diegoquintanav** [comment]
@polmonso Where is this failing?

**Comment by polmonso** [comment]
This is run manually when we're hole-filling
